 ! --------------------------------------------------- CP Optimizer 22.1.1.0 --
 ! Maximization problem - 60 variables, 283 constraints
 ! TimeLimit            = 1800
 ! Workers              = 8
 ! LogVerbosity         = Terse
 ! Initial process time : 0.01s (0.01s extraction + 0.00s propagation)
 !  . Log search space  : 348.4 (before), 348.4 (after)
 !  . Memory usage      : 698.8 kB (before), 698.8 kB (after)
 ! Using parallel search with 8 workers.
 ! ----------------------------------------------------------------------------
 !          Best Branches  Non-fixed    W       Branch decision
                        0         60                 -
 + New bound is 8
 *             4      887  0.06s        3      (gap is 100.0%)
 *             5      661  0.06s        5      (gap is 60.00%)
 *             6      882  0.06s        5      (gap is 33.33%)
 *             7     1920  0.06s        5      (gap is 14.29%)
Traceback (most recent call last):
  File "/home/AP/Cylic-Antibandwidth-Problem/CPLEX/CP/model.py", line 105, in <module>
    solution = mdl.solve(TimeLimit=1800, LogVerbosity='Quiet', Workers=8)
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/model.py", line 1289, in solve
    msol = solver.solve()
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver.py", line 714, in solve
    raise e
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver.py", line 707, in solve
    msol = self.agent.solve()
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver_local.py", line 213, in solve
    jsol = self._wait_json_result(EVT_SOLVE_RESULT)
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver_local.py", line 589, in _wait_json_result
    data = self._wait_event(evt)
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver_local.py", line 478, in _wait_event
    evt, data = self._read_message()
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver_local.py", line 648, in _read_message
    frame = self._read_frame(6)
  File "/home/AP/cplex_venv/lib/python3.10/site-packages/docplex/cp/solver/solver_local.py", line 708, in _read_frame
    raise CpoSolverException("Nothing to read from local solver process. Process seems to have been stopped (rc={}).".format(rc))
docplex.cp.solver.solver.CpoSolverException: Nothing to read from local solver process. Process seems to have been stopped (rc=-9).
